#!/usr/bin/python3
from art import *

Art = text2art("SHEEP ART", font='block', chr_ignore=True)

print('Content-Type: text/html')
print('')
print('<!DOCTYPE html>')
print('<html>')
print('<head>')
print('<meta charset="UTF-8">')
print('<title>My Python CGI Test</title>')
print('<style>')
print('body {')
print('  font-family: Arial, sans-serif;')
print('  background-color: #f0f0f0;')
print('}')
print('h1 {')
print('  color: #333;')
print('  text-align: center;')
print('}')
print('.art {')
print('  font-size: 32px;')
print('  line-height: 1.2;')
print('  margin: 40px auto;')
print('  background-color: #fff;')
print('  border: 2px solid #ccc;')
print('  padding: 20px;')
print('  text-align: center;')
print('}')
print('</style>')
print('</head>')
print('<body>')
print('<h1>My Python CGI Test</h1>')
print('<div class="art">{}</div>'.format(Art))
print('</body>')
print('</html>')